FROM mariadb:11.2.3
COPY my.cnf /etc/mysql/conf.d/

ENV MYSQL_DATABASE=buzz
ENV MYSQL_ROOT_PASSWORD=rootPassword
ENV MYSQL_DATABASE=buzz
ENV MYSQL_USER=buzzdbuser
ENV MYSQL_PASSWORD=buzzuserpassword

EXPOSE 3306