/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonCodeComponent: typeof import('./src/components/CommonCode/CommonCodeComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeComponent: typeof import('./src/components/Home/HomeComponent.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    NoPageComponent: typeof import('./src/components/NoPageComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
