version: '3.8'
services:
  # Database
  budget-bringer/database:
    image: mariadb:10.5
    build:
      context: .
      dockerfile: ./Resources/DataBase/Dockerfile
    container_name: budget-bringer-database
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: sgsRootPassword
      MYSQL_DATABASE: budget-bringer
      MYSQL_USER: sgsanalysisuser
      MYSQL_PASSWORD: analysisPassword
    networks:
      sgs-net:
        ipv4_address: 172.28.0.30
    restart: always
  # API 
  budget-bringer/api:
    build:
      context: .
      dockerfile: ./Apis/Dockerfile
    container_name: budget-bringer-api
    ports:
      - "8080:80"
      - "8081:81"
    environment:
      TZ: Asia/Seoul
    volumes:
      - .:/workspace
    networks:
      sgs-net:
        ipv4_address: 172.28.0.11
    restart: unless-stopped
networks:
  sgs-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
volumes:
  db_data:
