version: '3.8'
services: 
  # 데이터베이스 MariaDB
  database:
    image: sgs/budget-bringer-database
    build:
      context: ./Resources/DataBase
      dockerfile: Dockerfile
    container_name: budget-bringer-database
    ports:
      - "3309:3306"
    environment:
      TZ: Asia/Seoul
    networks:
      sgs-net:
        ipv4_address: 172.28.0.30
    restart: always
networks:
  sgs-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
  apiv2:
    image: apiv2
    build:
      context: .
      dockerfile: ApiV2/Dockerfile
