/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin/user/user-management': RouteRecordInfo<'/admin/user/user-management', '/admin/user/user-management', Record<never, never>, Record<never, never>>,
    '/admin/user/user-management-grid': RouteRecordInfo<'/admin/user/user-management-grid', '/admin/user/user-management-grid', Record<never, never>, Record<never, never>>,
    '/budget/budget-approved/budget-approved': RouteRecordInfo<'/budget/budget-approved/budget-approved', '/budget/budget-approved/budget-approved', Record<never, never>, Record<never, never>>,
    '/budget/budget-approved/budget-approved-grid': RouteRecordInfo<'/budget/budget-approved/budget-approved-grid', '/budget/budget-approved/budget-approved-grid', Record<never, never>, Record<never, never>>,
    '/budget/budget-plan/budget-plan': RouteRecordInfo<'/budget/budget-plan/budget-plan', '/budget/budget-plan/budget-plan', Record<never, never>, Record<never, never>>,
    '/budget/budget-plan/budget-plan-data-form': RouteRecordInfo<'/budget/budget-plan/budget-plan-data-form', '/budget/budget-plan/budget-plan-data-form', Record<never, never>, Record<never, never>>,
    '/budget/budget-plan/budget-plan-grid': RouteRecordInfo<'/budget/budget-plan/budget-plan-grid', '/budget/budget-plan/budget-plan-grid', Record<never, never>, Record<never, never>>,
    '/budget/budget-process/budget-process': RouteRecordInfo<'/budget/budget-process/budget-process', '/budget/budget-process/budget-process', Record<never, never>, Record<never, never>>,
    '/budget/budget-process/budget-process-approved/budget-process-grid-approved-above': RouteRecordInfo<'/budget/budget-process/budget-process-approved/budget-process-grid-approved-above', '/budget/budget-process/budget-process-approved/budget-process-grid-approved-above', Record<never, never>, Record<never, never>>,
    '/budget/budget-process/budget-process-approved/budget-process-grid-approved-below': RouteRecordInfo<'/budget/budget-process/budget-process-approved/budget-process-grid-approved-below', '/budget/budget-process/budget-process-approved/budget-process-grid-approved-below', Record<never, never>, Record<never, never>>,
    '/budget/budget-process/budget-process-approved-grid': RouteRecordInfo<'/budget/budget-process/budget-process-approved-grid', '/budget/budget-process/budget-process-approved-grid', Record<never, never>, Record<never, never>>,
    '/budget/budget-process/budget-process-business-unit/budget-process-grid-bu': RouteRecordInfo<'/budget/budget-process/budget-process-business-unit/budget-process-grid-bu', '/budget/budget-process/budget-process-business-unit/budget-process-grid-bu', Record<never, never>, Record<never, never>>,
    '/budget/budget-process/budget-process-grid': RouteRecordInfo<'/budget/budget-process/budget-process-grid', '/budget/budget-process/budget-process-grid', Record<never, never>, Record<never, never>>,
    '/budget/budget-process/budget-process-owner/budget-process-grid-pl-owner': RouteRecordInfo<'/budget/budget-process/budget-process-owner/budget-process-grid-pl-owner', '/budget/budget-process/budget-process-owner/budget-process-grid-pl-owner', Record<never, never>, Record<never, never>>,
    '/common-code/business-unit/business-unit': RouteRecordInfo<'/common-code/business-unit/business-unit', '/common-code/business-unit/business-unit', Record<never, never>, Record<never, never>>,
    '/common-code/business-unit/business-unit-grid': RouteRecordInfo<'/common-code/business-unit/business-unit-grid', '/common-code/business-unit/business-unit-grid', Record<never, never>, Record<never, never>>,
    '/common-code/cost-center/cost-center': RouteRecordInfo<'/common-code/cost-center/cost-center', '/common-code/cost-center/cost-center', Record<never, never>, Record<never, never>>,
    '/common-code/cost-center/cost-center-grid': RouteRecordInfo<'/common-code/cost-center/cost-center-grid', '/common-code/cost-center/cost-center-grid', Record<never, never>, Record<never, never>>,
    '/common-code/country-business-manager/country-business-manager': RouteRecordInfo<'/common-code/country-business-manager/country-business-manager', '/common-code/country-business-manager/country-business-manager', Record<never, never>, Record<never, never>>,
    '/common-code/country-business-manager/country-business-manager-grid': RouteRecordInfo<'/common-code/country-business-manager/country-business-manager-grid', '/common-code/country-business-manager/country-business-manager-grid', Record<never, never>, Record<never, never>>,
    '/common-code/country-business-manager/country-business-manager-units-grid': RouteRecordInfo<'/common-code/country-business-manager/country-business-manager-units-grid', '/common-code/country-business-manager/country-business-manager-units-grid', Record<never, never>, Record<never, never>>,
    '/common-code/sector/sector': RouteRecordInfo<'/common-code/sector/sector', '/common-code/sector/sector', Record<never, never>, Record<never, never>>,
    '/common-code/sector/sector-grid': RouteRecordInfo<'/common-code/sector/sector-grid', '/common-code/sector/sector-grid', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/home-drawer': RouteRecordInfo<'/home-drawer', '/home-drawer', Record<never, never>, Record<never, never>>,
    '/login/login': RouteRecordInfo<'/login/login', '/login/login', Record<never, never>, Record<never, never>>,
    '/login/login-dialog-confirm-logout': RouteRecordInfo<'/login/login-dialog-confirm-logout', '/login/login-dialog-confirm-logout', Record<never, never>, Record<never, never>>,
    '/login/login-logo': RouteRecordInfo<'/login/login-logo', '/login/login-logo', Record<never, never>, Record<never, never>>,
    '/logs/action/log-action': RouteRecordInfo<'/logs/action/log-action', '/logs/action/log-action', Record<never, never>, Record<never, never>>,
    '/logs/action/log-action-grid': RouteRecordInfo<'/logs/action/log-action-grid', '/logs/action/log-action-grid', Record<never, never>, Record<never, never>>,
    '/no-page': RouteRecordInfo<'/no-page', '/no-page', Record<never, never>, Record<never, never>>,
  }
}
