/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {RouteRecordInfo,} from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/budget/budget-approved/budget-approved': RouteRecordInfo<'/budget/budget-approved/budget-approved', '/budget/budget-approved/budget-approved', Record<never, never>, Record<never, never>>,
    '/budget/budget-approved/budget-approved-grid': RouteRecordInfo<'/budget/budget-approved/budget-approved-grid', '/budget/budget-approved/budget-approved-grid', Record<never, never>, Record<never, never>>,
    '/budget/budget-plan/budget-plan': RouteRecordInfo<'/budget/budget-plan/budget-plan', '/budget/budget-plan/budget-plan', Record<never, never>, Record<never, never>>,
    '/budget/budget-plan/budget-plan-grid': RouteRecordInfo<'/budget/budget-plan/budget-plan-grid', '/budget/budget-plan/budget-plan-grid', Record<never, never>, Record<never, never>>,
    '/budget/budget-process/budget-process': RouteRecordInfo<'/budget/budget-process/budget-process', '/budget/budget-process/budget-process', Record<never, never>, Record<never, never>>,
    '/budget/budget-process/budget-process-grid-pl-owner-500k-below': RouteRecordInfo<'/budget/budget-process/budget-process-grid-pl-owner-500k-below', '/budget/budget-process/budget-process-grid-pl-owner-500k-below', Record<never, never>, Record<never, never>>,
    '/common-code/common-code': RouteRecordInfo<'/common-code/common-code', '/common-code/common-code', Record<never, never>, Record<never, never>>,
    '/common-code/common-code-grid': RouteRecordInfo<'/common-code/common-code-grid', '/common-code/common-code-grid', Record<never, never>, Record<never, never>>,
    '/common-code/common-code-grid-renderer': RouteRecordInfo<'/common-code/common-code-grid-renderer', '/common-code/common-code-grid-renderer', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/home-drawer': RouteRecordInfo<'/home-drawer', '/home-drawer', Record<never, never>, Record<never, never>>,
    '/login/login': RouteRecordInfo<'/login/login', '/login/login', Record<never, never>, Record<never, never>>,
    '/login/login-dialog-confirm-logout': RouteRecordInfo<'/login/login-dialog-confirm-logout', '/login/login-dialog-confirm-logout', Record<never, never>, Record<never, never>>,
    '/login/login-logo': RouteRecordInfo<'/login/login-logo', '/login/login-logo', Record<never, never>, Record<never, never>>,
    '/logs/action/log-action': RouteRecordInfo<'/logs/action/log-action', '/logs/action/log-action', Record<never, never>, Record<never, never>>,
    '/no-page': RouteRecordInfo<'/no-page', '/no-page', Record<never, never>, Record<never, never>>,
  }
}
