/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/budget/budget-plan': RouteRecordInfo<'/budget/budget-plan', '/budget/budget-plan', Record<never, never>, Record<never, never>>,
    '/common-code/common-code': RouteRecordInfo<'/common-code/common-code', '/common-code/common-code', Record<never, never>, Record<never, never>>,
    '/common-code/common-code-grid-renderer': RouteRecordInfo<'/common-code/common-code-grid-renderer', '/common-code/common-code-grid-renderer', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/home-drawer': RouteRecordInfo<'/home-drawer', '/home-drawer', Record<never, never>, Record<never, never>>,
    '/login/login': RouteRecordInfo<'/login/login', '/login/login', Record<never, never>, Record<never, never>>,
    '/login/login-logo': RouteRecordInfo<'/login/login-logo', '/login/login-logo', Record<never, never>, Record<never, never>>,
    '/no-page': RouteRecordInfo<'/no-page', '/no-page', Record<never, never>, Record<never, never>>,
  }
}
