FROM mariadb:11.2.3
COPY my.cnf /etc/mysql/conf.d/

ENV MYSQL_DATABASE=sgsanalysis
ENV MYSQL_ROOT_PASSWORD=sgsanalysisPassW@rd
ENV MYSQL_USER=sgsanalysisuser
ENV MYSQL_PASSWORD=sgsanalysisuserPass

EXPOSE 3306