FROM mariadb:11.2.3
COPY my.cnf /etc/mysql/conf.d/

ENV MYSQL_DATABASE=sgs
ENV MYSQL_ROOT_PASSWORD=sgsRootPassword
ENV MYSQL_DATABASE=sgsanalysis
ENV MYSQL_USER=sgsanalysisuser
ENV MYSQL_PASSWORD=analysisPassword

EXPOSE 3306